version: '3.4'

services:
  
  tandemassesment:
    image: ${DOCKER_REGISTRY-}tandemassesment
    environment:
      - REDISSERVER=redis_image:6379
    build:
      context: .
      dockerfile: TandemAssesment/Dockerfile
    links:
        - "redis_image" 
    depends_on:
        - "redis_image"
  redis_image:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  tandemintegrationtest:
    image: ${DOCKER_REGISTRY-}tandemintegrationtest
    environment:
      - REDISSERVER=redis_image:6379
    build:
      context: .
      dockerfile: TandemIntegrationTest/Dockerfile
    links:
        - "tandemassesment" 
    depends_on:
        - "tandemassesment"
        - "redis_image"       
